### ISSUE TITLE
Design choice regarding user location

### ISSUE THREAD

**Issue by taehioum** [swsnu/swpp2019-team15#2]
Yesterday we decided that the component that gets user location should exist in every page.
Now I think getting user location only in the main page and the map page is a better idea, since

1) The main page (once we implement the feed feature) and the map page is the only page that requires user location.
2) The user should spend most of their time in the main page(again, once we implement the feed feature).

What are your thoughts?

**Comment by Minji1234** [comment]
I agree with you. And how about automatically push user's link to main page every 30 minutes if they don't use our web page. Then we can be more sure that they spend most of time in the main page. Also it will be of help implementing our machine learning feature because we can get users' GPS information more.
